# Generated by Django 4.2.3 on 2023-07-15 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Importance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sygnif', models.CharField(db_index=True, max_length=100, verbose_name='Importance')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Description')),
                ('finish_date', models.DateTimeField(verbose_name='Date')),
                ('finished', models.BooleanField(default=False, verbose_name='Finished')),
                ('signif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='todolist.importance', verbose_name='Importance')),
            ],
        ),
    ]
