# Generated by Django 4.2.7 on 2023-11-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['title', '-finish_date', 'finished']},
        ),
        migrations.AddField(
            model_name='importance',
            name='importance',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=20),
        ),
    ]
