# Generated by Django 4.2.7 on 2023-11-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_task_options_importance_importance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importance',
            name='slug',
        ),
    ]
