# Generated by Django 4.2.7 on 2023-12-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_remove_importance_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['signif', 'title', '-finish_date', 'finished']},
        ),
    ]
