# Generated by Django 4.2.7 on 2024-02-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tasks',
        ),
    ]
