# Generated by Django 4.2.7 on 2024-02-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_remove_profile_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/'),
        ),
    ]
